config/routes.rb
Rails.application.routes.draw do
  # public
  devise_for :members,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: 'public' do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "/members/my_page" => "members#my_page"
    get "/posts/my_posts" => "posts#my_posts"
    resources :members, except: [:new, :create] do
      member do
        get :favorite
      end
    end
    resources :posts do
      resources :comments, only: [:create, :destroy]
      collection do
        get "top"
        get "search"
      end
      resources :favorites, only: [:create, :destroy]
    end
  end

  # admin
  namespace :admin do
    root to: "homes#top"
    resources :members, only: [:show, :index]
    resources :posts, only: [:show, :index]
  end
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy  # 記事を削除するとお気に入りも削除
  belongs_to :member

  validates :title, presence: true
  validates :text, presence: true

  # member_idとpost_idが一致するfavoriteがなければ、nillを返す
  def favorited_by(member)
    Favorite.find_by(member_id: member.id, post_id: id)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1>投稿一覧</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th>タイトル</th>
            <th>ニックネーム</th>
            <th>投稿日</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <td><%= link_to post.title, admin_post_path(post.id) %></td>
            <td><%= post.member.member_name %></td>
            <td><%= post.created_at.strftime("%Y年%m月%d日") %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-md-12 text-center">
      <h2><%= @post.title %></h2>
    </div>
  </div>
  <div class="row my-3">
    <div class="col-md-12 text-center border">
      <%= @post.text %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-right">
      <%= link_to @post.member.member_name, admin_member_path(@post.member.id) %>
    </div>
  </div>
</div>