config/routes.rb
Rails.application.routes.draw do
  # public
  devise_for :members,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: 'public' do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "/members/my_page" => "members#my_page"
    get "/posts/my_posts" => "posts#my_posts"
    resources :members, except: [:new, :create] do
      member do
        get :favorite
      end
    end
    resources :posts do
      resources :comments, only: [:create, :destroy]
      collection do
        get "top"
        get "search"
      end
      resources :favorites, only: [:create, :destroy]
    end
  end

  # admin
  namespace :admin do
    root to: "homes#top"
    resources :members, only: [:show, :index]
    resources :posts, only: [:show, :index]
  end
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :post

  validates :comment_text, presence: true
end

app/models/commernt.rb
class Commernt < ApplicationRecord
  belongs_to :member
  belongs_to :pos
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :member
  belongs_to :post
  # 同じユーザーが同じ投稿を複数回お気に入り登録させないため。
  validates :member_id, uniqueness: { scope: :post_id }
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy  # 会員を削除するとお気に入りも削除

  validates :member_name, presence: true
  validates :gender, presence: true
  validates :age, presence: true
  validates :introduction, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy  # 記事を削除するとお気に入りも削除
  belongs_to :member

  validates :title, presence: true
  validates :text, presence: true

  # member_idとpost_idが一致するfavoriteがなければ、nillを返す
  def favorited_by(member)
    Favorite.find_by(member_id: member.id, post_id: id)
  end
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @posts = Post.all
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:member_name, :gender, :age, :introduction])
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BabyCare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="page-header">
      <% if member_signed_in? %>
        <div class="header-top-center">
          <%= link_to root_path, class:"header-title" do %>
            <div> babycare</div>
            <div class="header-sub-title"> ~不安のない子育てを~ </div>
          <% end %>
        </div>
        <div class="nav">
          <ul class="listes-right">
            <li class="header-mypage"><%= link_to members_my_page_path do %>マイページ<% end %></li>
            <li class="header-about"><%= link_to about_path do %>About<% end %></li>
            <li class="header-posts"><%= link_to posts_path do %>全ての投稿一覧<% end %></li>
            <li class="header-logout"><%= link_to destroy_member_session_path, method: :get do %>ログアウト<% end %></li>
          </ul>
        </div>
      <% elsif admin_signed_in? %>
        <div class="header-top-center">
          <%= link_to admin_root_path, class:"header-title" do  %>
            <div> babycare</div>
            <div class="header-sub-title"> ~不安のない子育てを~ </div>
          <% end %>
        </div>
        <div class="nav">
          <ul class="listes-right">
            <li class="header-members"><%= link_to admin_members_path do %>ユーザー一覧<% end %></li>
            <li class="header-posts"><%= link_to admin_posts_path do %>投稿一覧<% end %></li>
            <li class="header-logout"><%= link_to destroy_admin_session_path, method: :get do %>ログアウト<% end %></li>
          </ul>
        </div>
      <% else %>
        <div class="header-top-center">
          <%= link_to root_path, class:"header-title" do %>
            <div> babycare</div>
            <div class="header-sub-title"> ~不安のない子育てを~ </div>
          <% end %>
        </div>
        <div class="nav">
          <ul class="listes-right">
            <li class="header-signup"><%= link_to new_member_registration_path do %>新規登録<% end %></li>
            <li class="header-login"><%= link_to new_member_session_path do %>ログイン<% end %></li>
            <li class="header-about"><%= link_to about_path do %>About<% end %></li>
            <li class="header-posts"><%= link_to posts_path do %>投稿一覧<% end %></li>
          </ul>
        </div>
      <% end %>
          <div class="header-center">
            <div class="header-center-top">子育てのお悩み相談は</div>
            <div class="header-center-bottom">babycare</div>
          </div>
    </header>
    <main class="main">
      <%= yield %>
    </main>
    <footer class="footer">
      <div class="footer-text">© 2022 BabyCare lnc.All rights reserved.</div>
    </footer>
  </body>

</html>